/// Flutter icons EK_Icons
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  EK_Icons
///      fonts:
///       - asset: fonts/EK_Icons.ttf
///
/// 
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
///
import 'package:flutter/widgets.dart';

class EK_Icons {
  EK_Icons._();

  static const _kFontFam = 'EK_Icons';
  static const String? _kFontPkg = null;

  static const IconData arrowshape_left_fill = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrowshape_left = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrowshape_right_fill = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrowshape_right = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cart_fill = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cart = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hazardsign_fill = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hazardsign = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData horn_fill = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData horn = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pedal_accelerator_fill = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pedal_accelerator = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData steeringwheel = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gamecontroller_fill = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bluetooth_connected = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bluetooth_disabled = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData battery_25percent = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData battery_0percent = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData battery_50percent = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData battery_75percent = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData battery_100percent = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gamecontroller = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
